apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mb923/test-front:test-frontv1
          imagePullPolicy: Always
          env:
            - name: BACKEND_URL
              value: "http://backend-service:1337"
          ports:
            - containerPort: 3000
